jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install
      working-directory: C:\Users\saidh\my-app  # Make sure this matches the directory where pom.xml is located

    - name: Run tests
      run: mvn test
      working-directory:C:\Users\saidh\my-app # Repeat the correct directory here
